config/routes.rb
HealersConnnect::Application.routes.draw do
  devise_for :users

  root :to => 'website/home#home'

  devise_scope :user do
    get '/signin' => 'devise/sessions#new'
    get '/signout' => 'devise/sessions#destroy'
  end

  scope '/admin' do
    resources :instructors
    resources :centers
    resources :donations
    resources :event_schedules
    resources :events
    resources :manage_homes
    resources :courses do
      member do
        put :deactivate
        put :activate
      end
    end
    resources :workshops do
      resources :registrations do
        resources :registration_donations, only: [:index, :new, :create]
        collection do
          get :confirm_certify_all
          post :certify_all
        end
        member do
          get :confirm_certify
          post :certify
          put :deactivate
          put :activate
          get :export
        end
      end
    end
  end

  resources :courses, controller: 'website/courses', as: 'website_courses'
  resources :home, controller: 'website/home', as: 'website_home'
  resources :activities, controller: 'website/activities', as: 'website_activities'
  get 'courses/by_category/:id' => 'website/courses#category_wise_courses', as: :category_wise_courses
  post '/admin/donations/search' => 'donations#index', as: :search_donations
  post 'workshops/course/instructors' => 'workshops#course_instructors'
  post 'workshop_sessions/destroy' => 'workshops#destroy_workshop_session'
  post 'check_phone_number' => 'users#check_phone_number'
  get 'export_registrations' => 'registrations#export_registrations', as: :export_registrations
  get 'admin/donation/:id' => 'donations#export', as: :export_donation_pdf
  post 'admin/event_schedules/upload_photo' => 'event_schedules#upload_photo', as: :upload_photo
  post 'admin/events/upload_photo' => 'events#upload_photo', as: :upload_activity_photo
  delete 'admin/event_schedules/event_schedules/photo/:id' => 'event_schedules#remove_event_photo', as: :remove_event_photo
  delete 'admin/events/photo/:id' => 'events#remove_activity_photo', as: :remove_activity_photo
  get 'manage_homes/update_upcoming_workshop/:id' => 'manage_homes#update_upcoming_workshop'
  get 'manage_homes/update_upcoming_event/:id' => 'manage_homes#update_upcoming_event'
  get 'courses/detail/:id' => 'website/courses#detail', as: :course_detail
  get 'events/detail/:id' => 'website/events#show', as: :event_detail

  get 'admin/user_profiles' => 'user_profiles#index'
  get 'photos/events/:id/:style/:filename' => 'events#show_image', as: :event_image
  get 'photos/events/:event_id/gallery/:id/:style/:filename' => 'events#show_event_image_gallery', as: :event_image_gallery
  get 'photos/event_schedule_gallery/:event_schedule_id/:id/:style/:filename' => 'event_schedules#show_event_schedule_gallery', as: :event_schedule_gallery
  get 'photos/courses/:id/:style/:filename' => 'courses#show_course_image', as: :course_image
  get 'photos/courses/:id/:style/:filename' => 'website/courses#show_course_image', as: :website_course_image
  get 'photos/events/:id/:style/:filename' => 'website/activities#show_activity_image', as: :website_activity_image
  get 'photos/events/:event_id/gallery/:id/:style/:filename' => 'website/activities#show_event_image_gallery', as: :website_event_image_gallery
  get 'events' => 'website/events#index', as: :website_events
end

app/models/workshop.rb
class Workshop < ActiveRecord::Base
  attr_accessible :assistant_instructor_id, :center_id,
    :course_id, :instructor_id,
    :end_date, :start_date,
    :fees_after_session, :fees_before_session, :fees_on_session,
    :fees_on_rejoining, :fees_date,
    :location, :lat, :long, :contact
  attr_accessible :workshop_sessions_attributes

  belongs_to :course
  belongs_to :instructor
  belongs_to :assistant_instructor, class_name: 'Instructor'
  belongs_to :center
  has_many :workshop_sessions, dependent: :destroy
  has_many :registrations
  has_many :certificates

  accepts_nested_attributes_for :workshop_sessions, allow_destroy: true, reject_if: proc { |att| att[:session_start].blank? || att[:session_end].blank? || !att[:session_start].instance_of?(DateTime)}

  validates_presence_of :center_id, :course_id, :instructor_id, :fees_date, :location, :contact
  validates_presence_of :fees_before_session, :fees_after_session, :fees_on_session, :fees_on_rejoining
  validate :workshop_session_presence

  # Upcoming courses for homepage
  scope :upcoming_workshops, lambda { where("start_date >= ?", Date.today).order(:start_date) }
  scope :show_on_slider, upcoming_workshops.where(show_on_slider: true)
  scope :filter_by_center, ->(centers) { where(center_id: centers) }

  def eligibilities
    course.eligibilities
  end

  # certify all confirmed registrations
  # returns nil if activerecord invalid error is encountered
  # returns count of total confirmed registration if all are updated successfully
  def certify_all_confirmed_registrations
    registrations_to_confirm = registrations.confirmed.uncertified.freshers
    registration_confirmed_count = registrations_to_confirm.count
    begin
      ActiveRecord::Base.transaction do
        registrations_to_confirm.each { |reg| reg.certify }
      end
    rescue ActiveRecord::RecordInvalid => e
      logger.error "ERROR While: certifying all confirmed registrations"
      logger.error "#{e.backtrace.first}: #{e.message} (#{e.class})"
      registration_confirmed_count = e
    end
    registration_confirmed_count
  end

  def any_registration_awaiting_certification?
    !registrations.confirmed.uncertified.blank?
  end

  def donation_receivable(is_fresher, registration_date)
    if is_fresher
      if registration_date <= fees_date.to_date
        fees_before_session
      elsif registration_date < start_date.to_date
        fees_after_session
      else
        fees_on_session
      end
    else
      fees_on_rejoining
    end
  end

  def is_of?(course_alias)
    course.alias == course_alias.to_s
  end

  def timings
    session = workshop_sessions.first
    if session
      "#{session.session_start.strftime('%l:%M %p')} to #{session.session_end.strftime('%l:%M %p')}"
    end
  end

  private

  def workshop_session_presence
    errors.add(:workshop_sessions, "can't be blank") if workshop_sessions.blank?
  end

  # Prepare array of upcoming workshops for home slider
  def self.upcoming_workshops_for_slider
    workshops = []
    show_on_slider.each do |workshop|
      upcoming_workshop_hash = {}
      upcoming_workshop_hash[:image] = Rails.application.routes.url_helpers.website_course_image_path(style: :original, id: workshop.course.id, filename: workshop.course.avatar_file_name) if workshop.course.avatar_file_name.present?
      upcoming_workshop_hash[:name] = workshop.course.name
      upcoming_workshop_hash[:description] = workshop.course.description
      upcoming_workshop_hash[:id] = workshop.course_id
      upcoming_workshop_hash[:url] = Rails.application.routes.url_helpers.website_courses_path(workshop_id: workshop.id)
      upcoming_workshop_hash[:show_on_slider] = workshop.show_on_slider
      upcoming_workshop_hash[:start_date] = workshop.start_date
      upcoming_workshop_hash[:end_date] = workshop.end_date
      upcoming_workshop_hash[:timings] = workshop.timings
      upcoming_workshop_hash[:venue] = workshop.location
      workshops << upcoming_workshop_hash
    end
    workshops
  end
end

app/controllers/workshops_controller.rb
class WorkshopsController < ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource only: [:show, :edit, :update, :destroy]

  before_filter :workshop_from_params , only: [:show, :edit, :update, :destroy]
  before_filter :course_from_params, only: [:course_instructors]
  #before_filter :check_center_admin_access, only: [:edit, :update, :destroy]

  def index
    @page = params[:page] || 1
    if Registration.should_filter_by_center?(current_user)
      workshops = Workshop.filter_by_center(current_user.centers)
    else
      workshops = Workshop
    end
    @workshops =  workshops.page(params[:page]).per(Settings.pagination.per_page).order('start_date DESC')
  end

  def new
    @workshop = Workshop.new
    @instructors = Instructor.all(:order => 'name ASC')
  end

  def create
    session_date_arr = []
    params[:workshop][:workshop_sessions_attributes].each do |workshop|
      if workshop[:date].present?
        session_date_arr << workshop[:date]
        workshop[:session_start] = "#{workshop[:date]} #{workshop[:session_start]}".to_datetime
        workshop[:session_end] = "#{workshop[:date]} #{workshop[:session_end]}".to_datetime
      end
    end

    sorted_session_date_arr = session_date_arr.sort_by {|s| Date.parse s}
    if sorted_session_date_arr.present?
      params[:workshop][:start_date] =  sorted_session_date_arr.first.to_datetime
      params[:workshop][:end_date] =  sorted_session_date_arr.last.to_datetime
    end

    remove_date_before_save(params[:workshop][:workshop_sessions_attributes])
    @workshop  = Workshop.new(params[:workshop])
    @instructors = Instructor.all(:order => 'name ASC')
    respond_to do |format|
      if @workshop.save
        format.html {redirect_to workshops_path, notice: t('workshop.message.workshop_created', workshop: @workshop.course.name)}
      else
        format.html {render :new}
      end
    end
  end

  def edit
    @instructors = Instructor.order(:name)
  end

  def show
  end

  def update
    session_date_arr = []
    params[:workshop][:workshop_sessions_attributes].each do |workshop|
      if workshop[:date].present?
        session_date_arr << workshop[:date]
        workshop[:session_start] = "#{workshop[:date]} #{workshop[:session_start]}".to_datetime
        workshop[:session_end] = "#{workshop[:date]} #{workshop[:session_end]}".to_datetime
      end
    end

    sorted_session_date_arr = session_date_arr.sort_by {|s| Date.parse s}
    if sorted_session_date_arr.present?
      params[:workshop][:start_date] =  sorted_session_date_arr.first.to_datetime
      params[:workshop][:end_date] =  sorted_session_date_arr.last.to_datetime
    end

    remove_date_before_save(params[:workshop][:workshop_sessions_attributes])
    respond_to do |format|
      if @workshop.update_attributes(params[:workshop])
        format.html {redirect_to workshops_path, notice: t('workshop.message.workshop_updated', workshop: @workshop.course.name)}
      else
        @instructors = Instructor.order(:name)
        format.html {render :edit }
      end
    end
  end

  def destroy
    respond_to do |format|
      @workshop.destroy
      format.html {redirect_to workshops_path, notice: t('workshop.message.workshop_destroy', workshop: @workshop.course.name)}
    end
  end

  def destroy_workshop_session
    workshop_session = WorkshopSession.find(params[:id])
    @workshop = workshop_session.workshop
    workshop_session.destroy
  end

 def course_instructors
   respond_to do |format|
     @instructors = @course.instructors
     format.js
   end
 end

  private

  def workshop_from_params
    @workshop = Workshop.find(params[:id])
  end

  def course_from_params
    @course = Course.find(params[:id])
  end

  def remove_date_before_save(workshop_attrs)
    workshop_attrs.each do |workshop_attr|
      workshop_attr.delete(:date)
    end
  end
end

app/helpers/workshops_helper.rb
module WorkshopsHelper
  def session_start_dropdown(session_start)
    session_start_time = get_session_start_end_time(session_start)
    session_start_time = '09:00 AM' unless session_start_time.present?
    select_tag("workshop[workshop_sessions_attributes][][session_start]", options_for_select(get_options_session_start_end_dropdown, session_start_time), :prompt=>"--Select--", class: 'col-xs-10 col-sm-5')
  end

  def session_end_dropdown(session_end)
    session_end_time = get_session_start_end_time(session_end)
    session_end_time = '07:00 PM' unless session_end_time.present?
    select_tag("workshop[workshop_sessions_attributes][][session_end]", options_for_select(get_options_session_start_end_dropdown, session_end_time), :prompt=>"--Select--", class: 'col-xs-10 col-sm-5 margin-left-5')
  end

  def get_options_session_start_end_dropdown
    ['12:00 AM', '01:00 AM', '02:00 AM', '03:00 AM', '04:00 AM', '05:00 AM', '06:00 AM', '07:00 AM', '08:00 AM', '09:00 AM', '10:00 AM', '11:00 AM', '12:00 PM', '01:00 PM', '02:00 PM', '03:00 PM', '04:00 PM', '05:00 PM', '06:00 PM', '07:00 PM', '08:00 PM', '09:00 PM', '10:00 PM', '11:00 PM']
  end

  def get_session_start_end_time(session_start_end_time)
    session_start_end_time.strftime("%I:%M %p") if session_start_end_time.present?
  end

  def fees_date
    if @workshop.fees_date.present?
      date_formatted(@workshop.fees_date)
    else
      ''
    end
  end
end

app/views/workshops/_course_instructors_part.html.haml
- workshop_instructor = @workshop.present? ? @workshop.instructor_id : ''
- workshop_assistant_instructor = @workshop.present? ? @workshop.assistant_instructor_id : ''
.form-group
  %label.col-sm-3.control-label.no-padding-right #{t('workshop.caption.instructor')}
  .col-sm-9
    = select_tag 'workshop[instructor_id]', options_from_collection_for_select(@instructors, :id, :name, workshop_instructor),
    class: 'col-xs-10 col-sm-5',
    prompt: prompt_msg

.form-group
  %label.col-sm-3.control-label.no-padding-right #{t('workshop.caption.assistant_instructor')}
  .col-sm-9
    = select_tag 'workshop[assistant_instructor_id]', options_from_collection_for_select(@instructors, :id, :name,  workshop_assistant_instructor),
    class: 'col-xs-10 col-sm-5',
    prompt: prompt_msg

app/views/workshops/_form.html.haml
- @workshop ||= Workshop.new
- create_view = @workshop.new_record?
- workshop_sessions = @workshop.workshop_sessions.order(:session_start)
= hidden_field_tag 'clientUrlsFound', workshop_sessions.present?
= render partial: 'shared/error_messages', locals: { target: @workshop }
.row
  .col-xs-12
    = form_for @workshop,  html: {class: 'form-horizontal', role: 'form', id: 'clientForm'} do |f|
      = hidden_field_tag 'workshop[center_id]', current_user.center.id
      .space-4
      %form.form-horizontal#sample-form
        .form-group
          %label.col-sm-3.control-label.no-padding-right #{t('common.caption.course')}
          .col-sm-9
            = f.collection_select :course_id, Course.all(:order => 'name ASC'), :id, :name, { prompt: true }, { class: 'col-xs-5 col-sm-5' }
        #course_instructors_part
          = render partial: 'course_instructors_part', locals: {prompt_msg: t('instructors.caption.instructor_select_tag_prompt'), f: f}
        -#.form-group
          %label.col-sm-3.control-label.no-padding-right #{t('donation.caption.center')}
          .col-sm-9
            = f.collection_select :center_id, Center.all(:order => 'name ASC'), :id, :name, { prompt: true }, { class: 'col-xs-10 col-sm-5' }
        .row#session_controls
          - if workshop_sessions.present?
            #workshop_sessions
              = render :partial => 'workshop_sessions', locals: {workshop_sessions: workshop_sessions}
          .col-xs-9
            %label.col-sm-4.control-label.no-padding-right= t('workshop.caption.session')
            #culpritsNameContainer
              .wrapper-class
                .fieldCollection
                  .col-xs-2.margin-right-15
                    .input-group
                      = text_field_tag 'workshop[workshop_sessions_attributes][][date]', nil, id: 'id-date-picker-12', class: 'form-control date-picker'
                      %span.input-group-addon
                        %i.icon-calendar.bigger-110
                  .col-xs-4
                    = session_start_dropdown('')
                    = session_end_dropdown('')
              #addCulpritsBtn
                = link_to('javascript:void(0)', class: 'font-22') do
                  %i.icon-plus-sign
            .space-6

          #culpritsNameFieldTemplateContainer.hide
            .wrapper-class
              .fieldCollection{style: 'margin-top:-15px;'}
                .spacer30
                %label.col-sm-4.control-label.no-padding-right
                .col-xs-2.margin-right-15
                  .input-group
                    = text_field_tag 'workshop[workshop_sessions_attributes][][date]', nil, id: 'id-date-picker-1', class: 'form-control date-picker'
                    %span.input-group-addon
                      %i.icon-calendar.bigger-110
                .col-xs-4
                  = session_start_dropdown('')
                  = session_end_dropdown('')

            #culpritsNamesFieldRemoveBtnTemplateContainer.hide
              = link_to('javascript:void(0)', class: 'font-22') do
                %i.icon-minus-sign
        .space-6
        .form-group
          %label.col-sm-3.control-label.no-padding-right #{t('workshop.caption.fees')}
          .col-sm-4
            %label.col-sm-3.no-padding-right.common_form_lbl #{t('workshop.caption.fees_for_fresher')}
        .form-group
          %label.col-sm-3.control-label.no-padding-right
          .col-sm-9
            .col-sm-1
              %label.col-sm-3.control-label.no-padding-right #{t('workshop.caption.fees_before_session')}
            .col-sm-2
              .input-group
                = f.text_field :fees_date, id: 'fees_before-date-picker', class: 'form-control date-picker', value: @workshop.fees_date.try(:strftime, '%d/%m/%Y')
                %span.input-group-addon
                  %i.icon-calendar.bigger-110
            .col-sm-5
              = f.number_field :fees_before_session, class: 'col-xs-10 col-sm-5 text-right'
        .form-group
          %label.col-sm-3.control-label.no-padding-right
          .col-sm-9
            .col-sm-1
              %label.col-sm-3.control-label.no-padding-right #{t('workshop.caption.fees_after_session')}
            .col-sm-2
              = label_tag 'workshop_fees_after', fees_date, id: 'workshop_fees_after', class: 'common_form_lbl'
            .col-sm-5
              = f.number_field :fees_after_session, class: 'col-xs-10 col-sm-5 text-right'
        .form-group
          %label.col-sm-3.control-label.no-padding-right
          .col-sm-9
            .col-sm-1
              %label.col-sm-3.control-label.no-padding-right #{t('workshop.caption.fees_on_spot')}
            .col-sm-2
              = label_tag 'workshop_fees_spot', fees_date, id: 'workshop_fees_spot', class: 'common_form_lbl'
            .col-sm-5
              = f.number_field :fees_on_session, class: 'col-xs-10 col-sm-5 text-right'
        .form-group
          %label.col-sm-3.control-label.no-padding-right
          .col-sm-9
            .col-sm-3
              %label #{t('workshop.caption.fees_for_review')}
            .col-sm-5
              = f.number_field :fees_on_rejoining, class: 'col-xs-10 col-sm-5 text-right'
        .form-group
          %label.col-sm-3.control-label.no-padding-right #{t('center.caption.location')}
          .col-sm-4
            = f.text_field :location, class: 'col-xs-12', placeholder: t('center.caption.placeholder.location')
            = f.hidden_field :lat
            = f.hidden_field :long
        .form-group
          %label.col-sm-3.control-label.no-padding-right #{t('common.caption.contact')}
          .col-sm-4
            = f.text_field :contact, class: 'col-xs-12'
        .space-20
        .col-md-offset-3.col-md-9
          = f.submit t('common.caption.button.save'), class: 'btn btn-primary', title: t('workshop.caption.button.new')
          = link_to t('common.caption.button.cancel'), workshops_path, class: 'btn', title: t('common.caption.button.cancel')
%script{:src => '//maps.googleapis.com/maps/api/js?v=3&sensor=true&libraries=places&region=india', type: 'text/javascript'}
:javascript
  $(function(){
  initGoogleLocationSearchFields('workshop_location', 'workshop_long', 'workshop_lat', false);
  });

app/views/workshops/_workshop_details_page_header.html.haml
%i.icon-double-angle-right
= @workshop.course.name
- unless @workshop.start_date.blank?
  &nbsp;
  %i.icon-calendar.bigger-110
  = @workshop.start_date.try(:strftime, '%d/%m/%Y')
- unless @workshop.location.blank?
  &nbsp;
  %span.icon-map-marker.bigger-110
  = @workshop.location

app/views/workshops/_workshop_registration_list.html.haml
%tr.info
  %td.text-center<
    = date_formatted(workshop.start_date) rescue nil
  %td
    = date_formatted(workshop.end_date) rescue nil
  %td<
    = workshop.course.name
  /%td<
  /  = workshop.instructor.name
  %td
    = workshop.location
  %td.text-center<
    = link_to(t('common.caption.register'), new_workshop_registration_path(workshop), class: 'green', title: t('common.caption.register'))

app/views/workshops/_workshop_sessions.html.haml
- workshop_sessions.each_with_index do |workshop_session, index|
  - workshop_session_id = workshop_session.id
  - workshop_session_start = workshop_session.session_start
  - workshop_session_end = workshop_session.session_end
  = hidden_field_tag('workshop[workshop_sessions_attributes][][id]', workshop_session.id)

  .col-xs-9{id: "workshop_session_edit_#{index+1}"}
    %label.col-sm-4.control-label.no-padding-right
      = t('workshop.caption.session') unless workshop_sessions.present?
    #workshop-sessions-edit
      .wrapper-class
        .fieldCollection
          .col-xs-2.margin-right-15
            .input-group
              = text_field_tag 'workshop[workshop_sessions_attributes][][date]', '', id: 'id-date-picker-1', class: 'form-control date-picker',value: workshop_session.session_start.try(:strftime, '%d/%m/%Y')
              %span.input-group-addon
                %i.icon-calendar.bigger-110
          .col-xs-4
            = session_start_dropdown(workshop_session_start)
            = session_end_dropdown(workshop_session_end)
      .workshop-session-remove
        = link_to('javascript:void(0)', class: 'font-22',id: workshop_session_id, tag: "#{index+1}") do
          %i.icon-minus-sign

    .space-6

app/views/workshops/_workshops.html.haml
%tr.info
  %td<
    = serial_number(@page,workshop_counter)
  %td.text-center<
    = date_formatted(workshop.start_date)
  %td.text-center<
    = date_formatted(workshop.end_date)
  %td<
    = workshop.course.name
  %td<
    = workshop.instructor.name
  %td
    = workshop.center.name
  %td.text-center<
    .action-buttons
      = link_to(workshop_registrations_path(workshop), class: 'blue', title: 'View Registrations')  do
        %i.icon-eye-open.bigger-130
      - if can? :manage, Workshop
        = link_to(edit_workshop_path(workshop), class: 'green', title: t('common.caption.title.edit')) do
          %i.icon-pencil.bigger-130
        = link_to(workshop_path(workshop), method: :delete, :confirm=>t('workshop.message.remove') , class: 'red', title: t('common.caption.delete'))  do
          %i.icon-trash.bigger-130

app/views/workshops/course_instructors.js.haml
- prompt_msg = if @instructors.present?
  - t('instructors.caption.instructor_select_tag_prompt')
- else
  - t('instructors.caption.no_instrctor_found')
$('#course_instructors_part').html('#{escape_javascript render(partial: 'course_instructors_part', locals: {prompt_msg: prompt_msg})}');

app/views/workshops/destroy_workshop_session.js.haml
$('#WorkshopRegistrationTable').html('#{escape_javascript render(partial: 'workshop_sessions', locals: {workshop_sessions: @workshop.workshop_sessions})}');

app/views/workshops/edit.html.haml
.page-content
  .page-header
    %h1
      = t('workshop.page_content.header.edit')
  = render partial: 'form'

app/views/workshops/index.html.haml
.page-header
  %h1
    = t('workshop.page_content.header.index')
- if can? :create, Workshop
  .row
    .col-xs-12
      .btn-group.pull-right
        = link_to t('workshop.caption.button.new'), new_workshop_path, class: 'btn btn-sm btn-success', title: t('workshop.caption.button.new')
.row
  .space-6
  .col-xs-12
    .table-responsive
      %table.table.table-striped.table-bordered.table-hover
        %thead
          %tr
            %th{width: '5%'} #{t('common.caption.serial_number')}
            %th.text-center{width: '8%'} #{t('common.caption.start_date')}
            %th.text-center{width: '8%'} #{t('common.caption.end_date')}
            %th #{t('common.caption.course')}
            %th #{t('common.caption.instructor')}
            %th #{t('common.caption.center')}
            %th.text-center{width: '8%'} #{t('common.caption.manage')}
        - if @workshops.present?
          = render :partial => 'workshops', collection: @workshops, as: :workshop
        - else
          %tr
            %td{colspan: 7}
              .text-center
                %h3
                  = t('workshop.message.no_workshops_found')
    .col-xs-12
      .row
        .col-sm-6
        .col-sm-6
          .dataTables_paginate.paging_bootstrap
            = paginate @workshops

app/views/workshops/new.html.haml
.page-content
  .page-header.add_edit_page_header_margin
    %h1
      = t('workshop.page_content.header.new')
  = render partial: 'form'

app/views/workshops/show.html.haml
%h1 Workshops#show
%p Find me in app/views/workshops/show.html.haml