config/routes.rb
HealersConnnect::Application.routes.draw do
  devise_for :users

  root :to => 'website/home#home'

  devise_scope :user do
    get '/signin' => 'devise/sessions#new'
    get '/signout' => 'devise/sessions#destroy'
  end

  scope '/admin' do
    resources :instructors
    resources :centers
    resources :donations
    resources :event_schedules
    resources :events
    resources :manage_homes
    resources :courses do
      member do
        put :deactivate
        put :activate
      end
    end
    resources :workshops do
      resources :registrations do
        resources :registration_donations, only: [:index, :new, :create]
        collection do
          get :confirm_certify_all
          post :certify_all
        end
        member do
          get :confirm_certify
          post :certify
          put :deactivate
          put :activate
          get :export
        end
      end
    end
  end

  resources :courses, controller: 'website/courses', as: 'website_courses'
  resources :home, controller: 'website/home', as: 'website_home'
  resources :activities, controller: 'website/activities', as: 'website_activities'
  get 'courses/by_category/:id' => 'website/courses#category_wise_courses', as: :category_wise_courses
  post '/admin/donations/search' => 'donations#index', as: :search_donations
  post 'workshops/course/instructors' => 'workshops#course_instructors'
  post 'workshop_sessions/destroy' => 'workshops#destroy_workshop_session'
  post 'check_phone_number' => 'users#check_phone_number'
  get 'export_registrations' => 'registrations#export_registrations', as: :export_registrations
  get 'admin/donation/:id' => 'donations#export', as: :export_donation_pdf
  post 'admin/event_schedules/upload_photo' => 'event_schedules#upload_photo', as: :upload_photo
  post 'admin/events/upload_photo' => 'events#upload_photo', as: :upload_activity_photo
  delete 'admin/event_schedules/event_schedules/photo/:id' => 'event_schedules#remove_event_photo', as: :remove_event_photo
  delete 'admin/events/photo/:id' => 'events#remove_activity_photo', as: :remove_activity_photo
  get 'manage_homes/update_upcoming_workshop/:id' => 'manage_homes#update_upcoming_workshop'
  get 'manage_homes/update_upcoming_event/:id' => 'manage_homes#update_upcoming_event'
  get 'courses/detail/:id' => 'website/courses#detail', as: :course_detail
  get 'events/detail/:id' => 'website/events#show', as: :event_detail

  get 'admin/user_profiles' => 'user_profiles#index'
  get 'photos/events/:id/:style/:filename' => 'events#show_image', as: :event_image
  get 'photos/events/:event_id/gallery/:id/:style/:filename' => 'events#show_event_image_gallery', as: :event_image_gallery
  get 'photos/event_schedule_gallery/:event_schedule_id/:id/:style/:filename' => 'event_schedules#show_event_schedule_gallery', as: :event_schedule_gallery
  get 'photos/courses/:id/:style/:filename' => 'courses#show_course_image', as: :course_image
  get 'photos/courses/:id/:style/:filename' => 'website/courses#show_course_image', as: :website_course_image
  get 'photos/events/:id/:style/:filename' => 'website/activities#show_activity_image', as: :website_activity_image
  get 'photos/events/:event_id/gallery/:id/:style/:filename' => 'website/activities#show_event_image_gallery', as: :website_event_image_gallery
  get 'events' => 'website/events#index', as: :website_events
end

app/models/instructor.rb
class Instructor < ActiveRecord::Base
  attr_accessible :name, :email, :mobile, :course_ids
  validates_presence_of :name

  validates :email, presence: true, format:  {:with => /\A[^@]+@([^@\.]+\.)+[^@\.]+\z/}

  has_many :course_instructors
  has_many :courses, through: :course_instructors
  has_many :workshops
  has_many :event_schedules

  validates :mobile, numericality: { only_integer: true },
            length: { is: 10 }, allow_blank: true,
            format:  {:with => /^[1-9]/}

end

app/controllers/instructors_controller.rb
class InstructorsController < ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource

  #before_filter :required_access,  only: [:index, :new, :create, :edit, :update, :destroy]
  #before_filter :find_instructor, only: [:edit, :update, :destroy]

  def index
  end

  def new
    @instructor = Instructor.new
  end

  def create
    @instructor = Instructor.new(params[:instructor])
    if @instructor.save
      flash[:notice] = t('instructor.message.success.created')
      redirect_to instructors_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @instructor.update_attributes(params[:instructor])
      flash[:notice] = t('instructor.message.success.updated')
      redirect_to instructors_path
    else
      render :edit
    end
  end

  def destroy
    @instructor.destroy
    flash[:notice] = t('instructor.message.success.removed')
    redirect_to instructors_path
  end

  private
  def find_instructor
    @instructor = Instructor.find(params[:id])
  end

end

app/helpers/instructors_helper.rb
module InstructorsHelper
  def instructor_submit_button
    if @instructor.new_record? 
      t('instructor.caption.button.save')
    else
      t('instructor.caption.button.update')
    end
  end
end

app/views/instructors/_form.html.haml
- @instructor ||= Center.new
- create_view = @instructor.new_record?
- submit_btn_caption = ( create_view ? t('instructor.caption.button.new') : t('common.caption.button.save') )
- text_field_class = 'col-xs-10 col-sm-6'
= form_for @instructor, html: { class: 'form-horizontal', role: 'form'} do |f|
  = render partial: 'shared/error_messages', locals: { target: f.object }
  .row
    .col-xs-12
      .col-xs-10
        .form-group
          %label.col-sm-3.control-label.no-padding-right= t('common.caption.name')
          .col-sm-9
            = f.text_field :name, class: text_field_class
        .space-4
        .form-group
          %label.col-sm-3.control-label.no-padding-right= t('common.caption.email')
          .col-sm-9
            = f.email_field :email, class: text_field_class
        .space-4
        .form-group
          %label.col-sm-3.control-label.no-padding-right= t('common.caption.mobile')
          .col-sm-9
            = f.telephone_field :mobile, placeholder: t('common.10_digit_mobile_number'), class: text_field_class
        .space-4
        .form-group
          %label.col-sm-3.control-label.no-padding-right= t('instructor.caption.eligibilities')
          .col-sm-9
            = f.collection_select :course_ids, Course.all(order: 'name ASC'), :id, :name, {}, multiple: true, prompt: false, id: 'form-field-select-4', class: 'instructor-chosen-select chosen-select tag-input-style', data: { placeholder: '' }
        .form-group
          .col-md-offset-3.col-md-9
            = f.submit "#{submit_btn_caption}", class: 'btn btn-primary', title: "#{submit_btn_caption}"
            = link_to t('common.caption.button.cancel'), instructors_path, class: 'btn', title: t('common.caption.button.cancel')

app/views/instructors/edit.html.haml
.page-content
  .page-header.add_edit_page_header_margin
    %h1
      = t('instructor.page_content.header.edit')
  = render partial: 'form'

app/views/instructors/index.html.haml
.page-header
  %h1
    = t('instructor.page_content.header.index')
.row
  .col-xs-12
    .btn-group.pull-right.margin-bottom-10
      = link_to t('instructor.caption.button.new'), new_instructor_path, class: 'btn btn-sm btn-success', title: t('instructor.caption.button.new')
.row
  .col-xs-12
    .table-responsive
      %table#sample-table-2.table.table-striped.table-bordered.table-hover
        %thead
          %tr
            %th{width: '5%'} #{t('common.caption.serial_number')}
            %th{width: '27%'} #{t('common.caption.name')}
            %th{width: '10%'} #{t('common.caption.email')}
            %th.text-center{width: '10%'} #{t('common.caption.mobile')}
            %th.text-center{width: '10%'} #{t('common.caption.manage')}
        - if @instructors.present?
          - @instructors.each_with_index do |instructor, index|
            %tr
              %td= index + 1
              %td= instructor.name
              %td= instructor.email
              %td.text-center= instructor.mobile
              %td.text-center<
                .action-buttons
                  = link_to(edit_instructor_path(instructor), class: 'green', title: t('common.caption.title.edit')) do
                    %i.icon-pencil.bigger-130
                  = link_to(instructor_path(instructor), method: :delete, :confirm=>t('instructor.message.remove') , class: 'red', title: t('common.caption.delete'))  do
                    %i.icon-trash.bigger-130
        - else
          %tr
            %td{colspan: 6}
              .text-center
                %h3
                  = t('course.message.no_instructor_found')

app/views/instructors/new.html.haml
.page-content
  .page-header.add_edit_page_header_margin
    %h1
      = t('instructor.page_content.header.new')
  = render partial: 'form'