config/routes.rb
HealersConnnect::Application.routes.draw do
  devise_for :users

  root :to => 'website/home#home'

  devise_scope :user do
    get '/signin' => 'devise/sessions#new'
    get '/signout' => 'devise/sessions#destroy'
  end

  scope '/admin' do
    resources :instructors
    resources :centers
    resources :donations
    resources :event_schedules
    resources :events
    resources :manage_homes
    resources :courses do
      member do
        put :deactivate
        put :activate
      end
    end
    resources :workshops do
      resources :registrations do
        resources :registration_donations, only: [:index, :new, :create]
        collection do
          get :confirm_certify_all
          post :certify_all
        end
        member do
          get :confirm_certify
          post :certify
          put :deactivate
          put :activate
          get :export
        end
      end
    end
  end

  resources :courses, controller: 'website/courses', as: 'website_courses'
  resources :home, controller: 'website/home', as: 'website_home'
  resources :activities, controller: 'website/activities', as: 'website_activities'
  get 'courses/by_category/:id' => 'website/courses#category_wise_courses', as: :category_wise_courses
  post '/admin/donations/search' => 'donations#index', as: :search_donations
  post 'workshops/course/instructors' => 'workshops#course_instructors'
  post 'workshop_sessions/destroy' => 'workshops#destroy_workshop_session'
  post 'check_phone_number' => 'users#check_phone_number'
  get 'export_registrations' => 'registrations#export_registrations', as: :export_registrations
  get 'admin/donation/:id' => 'donations#export', as: :export_donation_pdf
  post 'admin/event_schedules/upload_photo' => 'event_schedules#upload_photo', as: :upload_photo
  post 'admin/events/upload_photo' => 'events#upload_photo', as: :upload_activity_photo
  delete 'admin/event_schedules/event_schedules/photo/:id' => 'event_schedules#remove_event_photo', as: :remove_event_photo
  delete 'admin/events/photo/:id' => 'events#remove_activity_photo', as: :remove_activity_photo
  get 'manage_homes/update_upcoming_workshop/:id' => 'manage_homes#update_upcoming_workshop'
  get 'manage_homes/update_upcoming_event/:id' => 'manage_homes#update_upcoming_event'
  get 'courses/detail/:id' => 'website/courses#detail', as: :course_detail
  get 'events/detail/:id' => 'website/events#show', as: :event_detail

  get 'admin/user_profiles' => 'user_profiles#index'
  get 'photos/events/:id/:style/:filename' => 'events#show_image', as: :event_image
  get 'photos/events/:event_id/gallery/:id/:style/:filename' => 'events#show_event_image_gallery', as: :event_image_gallery
  get 'photos/event_schedule_gallery/:event_schedule_id/:id/:style/:filename' => 'event_schedules#show_event_schedule_gallery', as: :event_schedule_gallery
  get 'photos/courses/:id/:style/:filename' => 'courses#show_course_image', as: :course_image
  get 'photos/courses/:id/:style/:filename' => 'website/courses#show_course_image', as: :website_course_image
  get 'photos/events/:id/:style/:filename' => 'website/activities#show_activity_image', as: :website_activity_image
  get 'photos/events/:event_id/gallery/:id/:style/:filename' => 'website/activities#show_event_image_gallery', as: :website_event_image_gallery
  get 'events' => 'website/events#index', as: :website_events
end

app/models/donation.rb
class Donation < ActiveRecord::Base
  default_scope order('created_at DESC')

  FOR_CENTER = 1
  FOR_FOOD_FOR_HUNGRY = 2
  attr_accessible :center_id, :description, :donation_type, :donor_name, :donor_email, :amount, :user_id
  attr_accessible :received_on
  acts_as_sequenced scope: :receipt_number
  acts_as_sequenced start_at: 1

  validates_presence_of :donor_name, :amount, :center_id, :received_on
  validates :donor_email, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  validates :amount, :numericality => true

  belongs_to :user
  belongs_to :center
  scope :for_center, ->(centers) { where(center_id: centers) }
  scope :received_by, ->(user) { where(user_id: user.id) }

  after_create :add_unique_donation_receipt_number

  def send_donation_notification_to_donor(user)
    begin
      HealersConnectMailer.delay.send_donation_notification_to_donor(self, user.email, center.name)
    rescue Exception => e
      Rails.logger.error "Failed to send email, email address: #{donor_email}"
      Rails.logger.error "#{e.backtrace.first}: #{e.message} (#{e.class})"
    end
  end

  def add_unique_donation_receipt_number
    update_attribute(:receipt_number, generate_unique_receipt_number)
  end

  def generate_unique_receipt_number
    "#{Time.now.year}#{Time.now.strftime('%m')}/#{"%04d" % sequential_id.to_s}"
  end

  # Search donations with Multiselectbox
  def self.search(params)
      donation_type = params[:donation_type].present? ? params[:donation_type].reject { |c| c.empty? } : []
      user_id = params[:user_id].present? ? params[:user_id].reject { |c| c.empty? } : []
      if donation_type.present? || user_id.present?
        donations = joins(:user).where("user_id in (?) OR donation_type in (?)",
                                                (user_id.present? ? user_id : []),
                                                (donation_type.present? ? donation_type : []))
      else
        donations = all
      end
      return donations
  end

  # Find donations by timline like weekly,monthly,yearly or by both for render chart
  def self.find_donation_by_timeline(timeline, donations)
    donations = donations.present? ? donations : Donation.all
    donations_by_timeline = case timeline
    when 'weekly'
    when 'monthly'
    when 'yearly'
      Hash[donations.group_by{ |u| u.created_at.beginning_of_month }.to_a.sort]
    end
  end

  # Find donations by "yearly" for chart
  def self.yearly_donations(donations)
    @array_for_yearly_chart = []
      donations.each do |month,donations|
        @array_for_yearly_chart << ["#{month.strftime('%B')}", donations.count.to_i]
    end
    @array_for_yearly_chart
  end
end

app/controllers/donations_controller.rb
class DonationsController < ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource only: [:index, :new, :create]

  #before_filter :find_donation, only: [:show, :export]
  #before_filter :required_access, only: [:index, :new, :create, :export]

  def index
    if params[:timeline].present?
      @timeline = params[:timeline]
      params[:user_id] = current_user.id if current_user.is_center_admin?
      if params[:donation].present?
        @donation_params = params[:donation]
        @donations = Donation.page(params[:page]).per(Settings.pagination.per_page).search(@donation_params)
      else
        donation_listing()
      end
    else
      donation_listing()
    end

    if @timeline.present?
      donations_by_timeline = Donation.find_donation_by_timeline(@timeline, @donations)
      @donation_chart = GoogleChartService.render_pie_chart(data_for_chart: Donation.yearly_donations(donations_by_timeline), chart_type: :bar, chart_name: 'Donations', required_formatter: true, col_x: 'Donation', col_y: 'Donations',  interactive: params[:interactive])
    end

  # Export PDF
    respond_to do |format|
      format.html
      format.js { render 'donation.js.erb'}
      format.pdf do
        render pdf: 'report',
               template: 'donations/donation_report_pdf.html.haml',
               dpi: '96',
               :show_as_html                   => params[:debug].present?,
               disable_internal_links: true, disable_external_links: true,
               :print_media_type => false, :no_background => false
        return 
      end
    end
  end

  def new
    @donation = Donation.new
    @centers = Center.all
  end

  def create
    @donation = Donation.new(params[:donation])
    if @donation.save
      @donation.send_donation_notification_to_donor(current_user)
      flash[:notice] = t('donation.message.success.donor_notification')
      redirect_to donations_path
    else
      @centers = Center.all
      render :new
    end
  end

  def export
    find_donation()
    authorize! :export_donation, @donation
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: 'donation',
               template: 'donations/donation_pdf.html.haml',
               dpi: '96',
               :show_as_html                   => params[:debug].present?,
               disable_internal_links: true, disable_external_links: true,
               :print_media_type => false, :no_background => false
        return
      end
    end
  end

  private
    def find_donation
      @donation = Donation.find(params[:id])
    end

    def donation_listing
      if current_user.is_center_admin?
        @donations = Donation.page(params[:page]).per(Settings.pagination.per_page).for_center(current_user.center_ids) 
      else if current_user.is_accountant?
        @donations = Donation.for_center(current_user.center_ids).received_by(current_user)
       else
        @donations = Donation.all
       end
      end
    end
end

app/helpers/donations_helper.rb
module DonationsHelper
  DONATION_TIMELINES = %w(weekly monthly yearly)
  def received_by_dropdown(donations, selected)
    options = donations.collect do |donation|
        [donation.user.email, donation.user.id]
    end
    select_tag("donation[user_id][]", options_for_select(options.uniq, selected[:user_id]), multiple: 'true', style: "display: none;", id: 'form-field-select-4', class: 'width-30 chosen-select donation_search_fields tag-input-style')
  end

  def active_donation_pill(timeline=nil)
    css_class = ''
    filter_timeline = params[:timeline]
    if timeline.present? && filter_timeline.present? && filter_timeline == timeline
      css_class = 'active'
    elsif timeline.blank? && filter_timeline.present? && !DONATION_TIMELINES.include?(filter_timeline)
      css_class = 'active'
    elsif timeline.blank? && filter_timeline.blank?
      css_class = 'active'
    end
    css_class
  end
end

app/views/donations/_donation_report.html.haml
.row
  .col-xs-12
    %table.table.table-striped.table-bordered.table-hover
      %thead
        %tr
          %th{width: '12%'} Receipt Number
          %th{width: '20%'} Donor
          %th{width: '25%'} Center
          %th{width: '10%'} Amount (&#x20B9;)
          %th{width: '15%'} Donation Type
          %th{width: '5%'} Received By
      - if @donations.present?
        - @donations.each do |donation|
          - donation_type = donation.donation_type == 1 ? 'For Center' : 'For Food for Hungry'
          %tr
            %td
              = donation.receipt_number
            %td
              = donation.donor_name
            %td
              = donation.center.name
            %td
              = donation.amount
            %td
              = donation_type
            %td
              = donation.user.email
      - else
        %tr
          %td{colspan: 7}
            .text-center
              %h3= t('course.message.no_donations_found')
.spacer15
.row.text-center
  .col-xs-12
    - if @donation_chart.present?
      .col-xs-10
        = image_tag @donation_chart.uri

app/views/donations/_donations.html.haml
- donation_type = donation.donation_type == 1 ? 'For Center' : 'For Food for Hungry'
%tr
  %td
    = donation.receipt_number
  %td
    = donation.donor_name
  %td
    = donation.center.name
  %td.text-right
    = donation.amount
  %td
    = donation.donation_type
  %td
    = donation.user.email
  %td
    = date_formatted(donation.received_on)
  %td.text-center<
    = link_to(export_donation_pdf_path(donation, format: :pdf), target: '_blank', title: t('donation.caption.title.save_as_pdf')) do
      %i.icon-print.bigger-130

app/views/donations/_form.html.haml
- text_field_class = 'col-xs-10 col-sm-6'
= form_for @donation, html: { class: 'form-horizontal', role: 'form'} do |f|
  = hidden_field_tag 'donation[user_id]', current_user.id
  = hidden_field_tag 'donation[center_id]', current_user.center.id
  = render partial: 'shared/error_messages', locals: { target: @donation }
  .row
    .col-xs-12
      .col-xs-10
        .form-group
          %label.col-xs-3.col-sm-3.control-label.no-padding-right= t('donation.caption.name')
          .col-sm-9
            = f.text_field :donor_name, class: text_field_class
        .form-group
          %label.col-sm-3.control-label.no-padding-right= t('donation.caption.email')
          .col-sm-9
            = f.text_field :donor_email, class: text_field_class
        .space-4
        .form-group
          %label.col-sm-3.control-label.no-padding-right= t('donation.caption.donation_type')
          .col-sm-9
            .control-group
              .radio
                %label
                  = f.radio_button :donation_type, 1, checked: true, class: 'ace'
                  %span.lbl= t('donation.caption.for_center_radio')
                %label
                  = f.radio_button :donation_type, 2, class: 'ace'
                  %span.lbl= t('donation.caption.for_food_for_hungry_radio')
        -#.space-4
        -#.form-group
          %label.col-sm-3.control-label.no-padding-right= t('donation.caption.center')
          .col-sm-9
            = select_tag t('donation.caption.center_select_tag'), options_from_collection_for_select(@centers, :id, :location), name: 'donation[center_id]',  prompt: t('donation.caption.center_select_tag_prompt')
        .form-group
          %label.col-sm-3.control-label.no-padding-right
            = t('donation.caption.amount')
            (&#x20B9;)
          .col-sm-9
            = f.text_field :amount, class: 'col-xs-3 margin-right-10 text-align-r'
        .form-group
          %label.col-sm-3.control-label.no-padding-right= t('common.caption.description')
          .col-sm-9
            = f.text_area :description, rows: 4, class: text_field_class
        .form-group
          %label.col-sm-3.control-label.no-padding-right= t('donation.caption.received_on')
          .col-sm-3
            .input-group
              = f.text_field :received_on, placeholder: t('donation.caption.placeholder_date'), class: 'form-control date-picker', id: 'id-date-picker-1', value: date_formatted(Date.today)
              %span.input-group-addon
                %i.icon-calendar.bigger-110
        .form-group
          %label.col-xs-3.col-sm-3.control-label.no-padding-right
          .col-xs-8
            = submit_tag t('donation.caption.button.save'), class: 'btn btn-primary', title: t('donation.caption.button.save')
            = link_to(t('common.caption.button.cancel'),donations_path , class: 'btn', title: t('common.caption.button.cancel'))

app/views/donations/donation.js.haml
$('#donation').html("#{escape_javascript(render :partial => 'donations', collection: @donations, as: :donation)}");

$('#paginator').html('#{escape_javascript(paginate(@donations, :remote => true, :param_name => "page").to_s)}');

app/views/donations/donation_pdf.html.haml
- donation_type = @donation.donation_type == 1 ? t('donation.caption.for_center_radio') : t('donation.caption.for_food_for_hungry_radio')
!!!
%html
  %head
    %meta{'http-equiv' => 'Content-Type', content: 'text/html; charset=utf-8'}
    = wicked_pdf_stylesheet_link_tag 'pdf/ace.min'
    = wicked_pdf_stylesheet_link_tag 'pdf/bootstrap'
    = wicked_pdf_stylesheet_link_tag 'pdf/custom'
  %body
    #wrap
      %header
      %main{role: 'main'}
        .main-container
          .main-container-inner
            .main-content
              .page-content
                %h2
                  %b= t('donation.caption.pdf.title')
                .space-16
                .row
                  .col-xs-12
                    .form-group
                      %label.h4
                        %b= t('donation.caption.pdf.receipt_no')
                      %label.h4= @donation.receipt_number
                .row
                  .col-xs-12
                    .form-group
                      %label.h4
                        %b= t('donation.caption.pdf.name')
                      %label.h4= @donation.donor_name.capitalize
                .row
                  .col-xs-12
                    .form-group
                      %label.h4
                        %b= t('donation.caption.pdf.email')
                      %label.h4= @donation.donor_email
                .row
                  .col-xs-12
                    .form-group.pull-left
                      %label.h4
                        %b
                          = t('donation.caption.pdf.amount')
                          (&#x20B9;):
                      %label.h4
                        = @donation.amount
                .row
                  .col-xs-12
                    .form-group.pull-left
                      %label.h4
                        %b= t('donation.caption.pdf.received_by')
                      %label.h4
                        = @donation.user.email
                .row
                  .col-xs-12
                    .form-group.pull-left
                      %label.h4
                        %b= t('donation.caption.pdf.donation_type')
                      %label.h4
                        = donation_type
                .row
                  .col-xs-12
                    .form-group.pull-left
                      %label.h4
                        %b= t('donation.caption.pdf.center')
                      %label.h4
                        = @donation.center.name
                - if @donation.description.present?
                  .row
                    .col-xs-12
                      .form-group.pull-left
                        %label.h4
                          %b= t('donation.caption.pdf.description')
                        %label.h4
                          = @donation.description

app/views/donations/donation_report_pdf.html.haml
!!!
%html
  %head
    %meta{"http-equiv" => "Content-Type", :content => "text/html; charset=utf-8"}
    = wicked_pdf_stylesheet_link_tag "pdf/ace.min"
    = wicked_pdf_stylesheet_link_tag "pdf/bootstrap"
    = wicked_pdf_stylesheet_link_tag "pdf/custom"
  %body
    #wrap
      %header
      %main{:role => "main"}
        .main-container
          .main-container-inner
            .main-content
              .page-content
                .page-header
                  %h1.text-center
                    = t('donation.caption.pdf.report_title')
                .spacer15
                = render partial: 'donations/donation_report.html.haml', locals: { pdf: true }

app/views/donations/index.html.haml
- @donation_params ||= Donation.new
.page-header
  %h1
    = t('donation.caption.donations')
    - unless current_user.is_super_admin?
      .btn-group.pull-right.btn_reports_export_margin
        = link_to(t('donation.caption.button.new'), new_donation_path, class: 'btn btn-success btn-sm',title: t('donation.caption.button.new'))
.row
  .col-xs-12
    %ul.nav.nav-pills#registrations_container
      %li{class: active_donation_pill('weekly')}
        = link_to 'Weekly', 'javascript:void(0)'
      %li{class: active_donation_pill('monthly')}
        = link_to 'Monthly', 'javascript:void(0)'
        -#donations_path(timeline: 'monthly')
      %li{class: active_donation_pill('yearly')}
        = link_to 'Yearly', donations_path(timeline: 'yearly')
      %li{class: active_donation_pill}
        = link_to 'All', donations_path
    - if @donations.present?
      .btn-group.pull-right.btn_registration_new_margin
        = form_tag(donations_path(format: :pdf), method: :get, target: "_blank", class: 'form-horizontal', id: 'donationExportPdfForm') do
          = hidden_field_tag 'timeline', @timeline
          = hidden_field_tag 'interactive', false
          - if @donation_params[:donation_type].present?
            - @donation_params[:donation_type].each do |donation_type|
              = hidden_field_tag 'donation[donation_type][]', donation_type
          - else
            = hidden_field_tag 'donation[user_id][]', ''

          - if @donation_params[:user_id].present?
            - @donation_params[:user_id].each do |user_id|
              = hidden_field_tag 'donation[user_id][]', user_id
          - else
            = hidden_field_tag 'donation[user_id][]', ''
          - if current_user.is_center_admin?
            = link_to 'javascript:;', id: 'export_donation', class: 'donation_export_link', title: t('donation.caption.title.export')  do
              %i.icon-print.bigger-130
    .space-20
- if @timeline.present?
  .row
    .col-xs-12
      = form_tag(search_donations_path, method: :post, class: 'form-horizontal', id: 'clientFormCaseMgrs', multipart: true) do
        = hidden_field_tag 'timeline', @timeline
        .col-xs-6
          %label.margin-right-10
            = t('donation.caption.donation_type')
          = select_tag("donation[donation_type][]", options_for_select([["For Center", '1'], ["For Food for Hungry", '2']],  @donation_params[:donation_type]), multiple: 'true', style: "display: none;", id: 'form-field-select-4', class: 'width-30 chosen-select donation_search_fields tag-input-style')
        .col-xs-6
          %label.margin-right-10.margin-left-5
            = t('donation.caption.received_by')
          = received_by_dropdown(Donation.all, @donation_params)
          = submit_tag t('donation.caption.button.search'), class: 'btn btn-sm btn-primary no-radius text-center donation_search_fields', title: t('donation.caption.button.search')
      .col-xs-2
  .space-20
.row
  .col-xs-12
    .space-6
    .table-responsive
      %table.table.table-striped.table-bordered.table-hover
        %thead
          %tr
            %th{width: '12%'} #{t('donation.caption.receipt_no')}
            %th{width: '20%'} #{t('donation.caption.name')}
            %th{width: '25%'} #{t('donation.caption.center')}
            %th.text-center{width: '10%'} #{t('donation.caption.amount')} (&#x20B9;)
            %th{width: '15%'} #{t('donation.caption.donation_type')}
            %th{width: '5%'} #{t('donation.caption.received_by')}
            %th{width: '10%'}= t('donation.caption.received_on')
            %th
        %tbody#donation
          - if @donations.present?
            = render :partial => 'donations', collection: @donations, as: :donation
          - else
            %tr
              %td{colspan: 8}
                .text-center
                  %h3= t('donation.message.no_donations_found')
    .col-xs-12
      .row
        .col-sm-6
        .col-sm-6
          .dataTables_paginate.paging_bootstrap
            #paginator
              = paginate @donations, :remote => true ,:param_name => "page"           
.space-20
-#- if @donation_chart
  .row
    .col-xs-12
      #donation_chart
        = render_chart(@donation_chart, 'donation_chart')

app/views/donations/new.html.haml
.page-header
  %h1= t('donation.captions.new_donation')
= render :partial => 'form'