config/routes.rb
HealersConnnect::Application.routes.draw do
  devise_for :users

  root :to => 'website/home#home'

  devise_scope :user do
    get '/signin' => 'devise/sessions#new'
    get '/signout' => 'devise/sessions#destroy'
  end

  scope '/admin' do
    resources :instructors
    resources :centers
    resources :donations
    resources :event_schedules
    resources :events
    resources :manage_homes
    resources :courses do
      member do
        put :deactivate
        put :activate
      end
    end
    resources :workshops do
      resources :registrations do
        resources :registration_donations, only: [:index, :new, :create]
        collection do
          get :confirm_certify_all
          post :certify_all
        end
        member do
          get :confirm_certify
          post :certify
          put :deactivate
          put :activate
          get :export
        end
      end
    end
  end

  resources :courses, controller: 'website/courses', as: 'website_courses'
  resources :home, controller: 'website/home', as: 'website_home'
  resources :activities, controller: 'website/activities', as: 'website_activities'
  get 'courses/by_category/:id' => 'website/courses#category_wise_courses', as: :category_wise_courses
  post '/admin/donations/search' => 'donations#index', as: :search_donations
  post 'workshops/course/instructors' => 'workshops#course_instructors'
  post 'workshop_sessions/destroy' => 'workshops#destroy_workshop_session'
  post 'check_phone_number' => 'users#check_phone_number'
  get 'export_registrations' => 'registrations#export_registrations', as: :export_registrations
  get 'admin/donation/:id' => 'donations#export', as: :export_donation_pdf
  post 'admin/event_schedules/upload_photo' => 'event_schedules#upload_photo', as: :upload_photo
  post 'admin/events/upload_photo' => 'events#upload_photo', as: :upload_activity_photo
  delete 'admin/event_schedules/event_schedules/photo/:id' => 'event_schedules#remove_event_photo', as: :remove_event_photo
  delete 'admin/events/photo/:id' => 'events#remove_activity_photo', as: :remove_activity_photo
  get 'manage_homes/update_upcoming_workshop/:id' => 'manage_homes#update_upcoming_workshop'
  get 'manage_homes/update_upcoming_event/:id' => 'manage_homes#update_upcoming_event'
  get 'courses/detail/:id' => 'website/courses#detail', as: :course_detail
  get 'events/detail/:id' => 'website/events#show', as: :event_detail

  get 'admin/user_profiles' => 'user_profiles#index'
  get 'photos/events/:id/:style/:filename' => 'events#show_image', as: :event_image
  get 'photos/events/:event_id/gallery/:id/:style/:filename' => 'events#show_event_image_gallery', as: :event_image_gallery
  get 'photos/event_schedule_gallery/:event_schedule_id/:id/:style/:filename' => 'event_schedules#show_event_schedule_gallery', as: :event_schedule_gallery
  get 'photos/courses/:id/:style/:filename' => 'courses#show_course_image', as: :course_image
  get 'photos/courses/:id/:style/:filename' => 'website/courses#show_course_image', as: :website_course_image
  get 'photos/events/:id/:style/:filename' => 'website/activities#show_activity_image', as: :website_activity_image
  get 'photos/events/:event_id/gallery/:id/:style/:filename' => 'website/activities#show_event_image_gallery', as: :website_event_image_gallery
  get 'events' => 'website/events#index', as: :website_events
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_filter :authenticate_user!, except: [:show_course_image]
  load_and_authorize_resource except: [:show_course_image]

  #before_filter :course_from_params, only: [:show, :edit, :update,:destroy, :deactivate, :activate]
  #before_filter :required_access, only: [:index, :create, :show, :edit, :update, :activate, :deactivate, :destroy]

  def index
    @page = params[:page] || 1
    @courses  = @courses.page(params[:page]).per(Settings.pagination.per_page).order('created_at ASC')
  end

  def new
    redirect_to courses_path
  end

  def create
    @course  = Course.new(params[:course])
    @course_categories  = CourseCategory.all
    respond_to do |format|
      if @course.save
        format.html { redirect_to courses_path, notice: t('course.message.course_created', course: @course.name) }
      else
        format.html { render :new }
      end
    end
  end

  def show
  end

  def edit
    @course_categories = CourseCategory.all
  end

  def update
    respond_to do |format|
      if @course.update_attributes(params[:course])
        format.html { redirect_to courses_path, notice: t('course.message.course_updated', course: @course.name) }
      else
        @course_categories = CourseCategory.all
        format.html { render :edit }
      end
    end
  end

  def show_course_image
    render :text => open(Course.find(params[:id]).avatar.path(params[:style].to_sym), "rb").read
  end

  def deactivate
    update_course_status(:deactivate)
  end

  def activate
    update_course_status(:activate)
  end

  def destroy
    respond_to do |format|
      course_name = @course.name
      @course.destroy
      format.html { redirect_to courses_path, notice: t('course.message.course_destroy', course: course_name) }
    end
  end

  private

  def course_from_params
    @course = Course.find(params[:id])
  end

  def update_course_status(action)
    respond_to do |format|
      status, message = case action
                        when :activate
                          [true, t('course.message.course_activate', course: @course.name)]
                        when :deactivate
                          [false, t('course.message.course_deactivate', course: @course.name)]
                        else
                        end
        @course.update_status(status)
        format.html { redirect_to courses_path, notice: message }
    end
  end

end

app/controllers/website/courses_controller.rb
class Website::CoursesController < ApplicationController
  before_filter :course_from_params , only: [:detail]
  layout 'home'

  def index
    workshop = Workshop.find_by_id(params[:workshop_id])
    @courses = Course.find_all_by_course_category_id(CourseCategory.first.id).sort_by(&:id)

    if workshop.present?
      @course = workshop.course
    else
      @course = @courses.first
    end
  end

  def category_wise_courses
    respond_to do |format|
      @courses = Course.find_all_by_course_category_id(params[:id]).sort_by(&:id)
      @course = Course.find(@courses.first)
      format.js {
          render file: 'website/courses/category_wise_courses'
      }
    end
  end

  def show
    respond_to do |format|
      @course = Course.find(params[:id])
      format.js {
        render file: 'website/courses/category_wise_courses'
      }
    end
  end

  def detail
  end

  def show_course_image
    render :text => open(Course.find(params[:id]).avatar.path(params[:style].to_sym), "rb").read
      format.js {
        render file: 'website/courses/category_wise_courses'
      }
  end

  private

  def course_from_params
    @course = Course.find(params[:id])
  end
end

app/helpers/courses_helper.rb
module CoursesHelper
  def render_course_eligibility(aliases)
    aliases_split = aliases.split(',')
    if aliases_split.include?('16+')
      '16+ years'
    else
      Course.by_alias(aliases_split).map(&:name).join(', ')
    end
  end
end

app/views/courses/_courses.html.haml
%tr.info
  %td<
    = serial_number(@page,course_counter)
  %td<
    = link_to course.name, edit_course_path(course)
  %td<
    = course.course_category.name if course.course_category.present?
  %td.text-right<
    = course.donation
  %td.text-right<
    = course.review_donation
  %td.text-center<
    .visible-md.visible-lg.hidden-sm.hidden-xs.action-buttons
      = link_to(edit_course_path(course), class: 'green', title: t('common.caption.title.edit')) do
        %i.icon-pencil.bigger-130
      - if course.status
        = link_to(deactivate_course_path(course), method: :put, data: { confirm: t('course.message.deactivate_confirm_message') }, title: t('common.caption.deactivate')) do
          %i.icon-pause.bigger-130
      - else
        = link_to(activate_course_path(course), method: :put, data: { confirm: t('course.message.activate_confirm_message') }, title: t('common.caption.activate')) do
          %i.icon-play.bigger-130

app/views/courses/_form.html.haml
- @course ||= Course.new
- create_view = @course.new_record?
= render partial: 'shared/error_messages', locals: { target: @course }
.row
  .col-xs-12
    = form_for @course,  html: {class: 'form-horizontal', role: 'form'} do |f|
      .space-4
      .form-group
        %label.col-sm-2.control-label.no-padding-right{for: 'form-input-readonly'} #{t('common.caption.description')}
        .col-xs-10.col-sm-4
          = f.text_area :description, rows: 4, class: 'form-control', :class => 'ckeditor'
      .space-4
      .form-group
        %label.col-sm-2.control-label.no-padding-right{for: 'form-field-1'} #{t('course.caption.donation')}
        .col-xs-10.col-sm-1
          = f.text_field :donation, class: 'input-sm course_textbox_tex_align', size: '0'
        %label.col-sm-3.control-label.text-left{for: 'form-field-1'} #{t('course.caption.review_donation')}
        .col-sm-2
          = f.text_field :review_donation, class: 'input-sm course_textbox_tex_align', size: '0'
      .space-4
      .form-group
        %label.col-sm-2.control-label.no-padding-right{for: 'form-field-1'} #{t('common.caption.image')}
        .col-xs-10.col-sm-4
          = f.file_field :avatar
      - if @course.avatar.present?
        .form-group#course_avatar_part
          %label.col-sm-2.control-label.no-padding-right
          .col-sm-9
            = image_tag course_image_path(style: :medium, id: @course.id, filename: @course.avatar_file_name)
      .form-group
        %label.col-sm-2.control-label.no-padding-right
        .col-sm-9
          %img(src='' id='preview_course_avatar' style='display:none;')

      .form-group
        %label.col-sm-2.control-label.no-padding-right
        .col-xs-10.col-sm-4
          = f.submit t('common.caption.button.save'), class: 'btn btn-primary', title: t('common.caption.button.save')
          = link_to(t('common.caption.button.cancel'),courses_path , class: 'btn', title: t('common.caption.button.cancel'))

app/views/courses/edit.html.haml
.page-header
  %h1
    = t('course.caption.edit_course')
    %small
      %i.icon-double-angle-right
      %b
        = @course.name
      |
      #{t('course.caption.eligibility')}:
      = render_course_eligibility(@course.eligibility)
= render :partial => 'form'

app/views/courses/index.html.haml
.page-header
  %h1
    = t('course.caption.courses')
.row
  .space-6
  .col-xs-12
    .table-responsive
      %table.table.table-striped.table-bordered.table-hover
        %thead
          %tr
            %th{width: '7%'} #{t('common.caption.serial_number')}
            %th #{t('common.caption.name')}
            %th #{t('course.caption.course_category')}
            %th.text-center #{t('course.caption.donation')}
            %th.text-center #{t('course.caption.review_donation')}
            %th.text-center #{t('common.caption.manage')}
        - if @courses.present?
          = render :partial => 'courses', collection: @courses, as: :course
        - else
          %tr
            %td{colspan: 6}
              .text-center
                %h3
                  = t('course.message.no_courses_found')
    .col-xs-12
      .row
        .col-sm-6
        .col-sm-6
          .dataTables_paginate.paging_bootstrap
            = paginate @courses

app/views/courses/new.html.haml
.page-header
  %h1
    = t('course.caption.new_course')
= render :partial => 'form'